### ISSUE TITLE
Start documentation site

### ISSUE THREAD

**Issue by tmc** [tmc/langchaingo#104]
We should get a Docusaurus docs site going.

**Comment by Struki84** [comment]
Hi! We touched briefly on the subject on discord, I saw there was some discussion ([#21](https://github.com/tmc/langchaingo/issues/21)) about the tool we would use, Docusaurus then?  :)

**Comment by tmc** [comment]
> Hi! We touched briefly on the subject on discord, I saw there was some discussion ([#21](https://github.com/tmc/langchaingo/issues/21)) about the tool we would use, Docusaurus then?  :) 

Yes!

**Comment by FluffyKebab** [comment]
I can start working on this.

**Comment by Struki84** [comment]
That would be awesome, I don't have any experience with Docusarus and how to set it up, (was looking into it)if you can do that, I can start adding content as soon as it's set up ;). I'm guessing we are going to copy the structure and format from py and js docs?
