### ISSUE TITLE
Introduce callbacks concept

### ISSUE THREAD

**Issue by bdqfork** [tmc/langchaingo#108]
Note that langchain uses callbackmanagers to track the entire process of execution, may be we need too?

https://python.langchain.com/en/latest/modules/callbacks/getting_started.html

![image](https://github.com/tmc/langchaingo/assets/23702980/e34ba403-debb-46ed-bb03-95292785aab4)

**Comment by bdqfork** [comment]
@tmc What do you think of this proposal? If possible, I will try to  implementation it.

**Comment by waltcow** [comment]
I think callback can be anther option when compare with logger

**Comment by FluffyKebab** [comment]
Fixed by #257
