### ISSUE TITLE
pinecone-withGrpc-option is not exported from package. Is this being worked on?

### ISSUE THREAD

**Issue by cduggn** [tmc/langchaingo#130]
The `withGrpc()` function is not exported from the `pinecone` package. In effect it cannot be used by client code outside of that package. Is this something that is being worked on?  

Both of `AddSimilarity` and `SimilaritySearch` functions have superfluous code blocks which check if the `useGRPC` flag is set.

**Comment by FluffyKebab** [comment]
I unexported the option when I initially wrote the code because I was unable to make the grpc client work. I think I got an error about a malformed http header. I dont think the grpc client is currently being worked on, but testing and debugging of this is needed.

**Comment by cduggn** [comment]
Would it be helpful to follow some of the practices from the upstream libraries for this type of situation? Experimental features could be located in an `experimental` package.  Non-experimental but not fully implemented features could live in the standard packages but could return a `NotImplementedError` for any of the elements of the API that have not been implemented. Just a suggestion

**Comment by tmc** [comment]
@cduggn we have the exp tree to represent that. I'm happy to copy the pinecone client to the exp tree and strip the gRPC references from the non-exp client. contributions here are certainly welcomed.

**Comment by cduggn** [comment]
great stuff @tmc , I didn't notice that package. I'll use in the future. I will try look into gRPC issue sometime this week, so probably ok leave the code as is for now.
