### ISSUE TITLE
[feature request] pass in openai.Option options into embeddings.NewOpenAI() (to be able to use openai.WithToken(OPENAI_API_KEY) without env var)

### ISSUE THREAD

**Issue by heiningair** [tmc/langchaingo#159]
I was wondering if some others would also agree that it would make sense to refactor the embeddings NewOpenAI function so that you can pass in the OPENAI_API_KEY as an openai.Option ( like done in the openaillm.go -> NewChat(opts ...Option) )  and do not depend on setting the OPENAI_API_KEY as environment variable.

This would make sense so you can actually make use of your users apiKeys for embedding documents.

[embeddings/openai.go](https://github.com/tmc/langchaingo/blob/main/embeddings/openai.go)
[embeddings/openai_test.go](https://github.com/tmc/langchaingo/blob/main/embeddings/embedding_test.go)
[llms/openai/openaillm.go](https://github.com/tmc/langchaingo/blob/main/llms/openai/openaillm.go)

**Comment by cduggn** [comment]
@heiningair rather than modifying the existing code, would it be viable for your use case to set the environment variable programmatically? Same is described [here](https://python.langchain.com/docs/modules/model_io/models/llms/integrations/openai)in the upstream Python version of the library

**Comment by heiningair** [comment]
@cduggn thanks for this suggestion. Unfortunately this wouldnt solve what i plan to do, since it would overwrite the actual apiKey everytime a user creates an instance of the openai client. It would lead to issues in my multi threaded multi user environment, in which every user should be able to set their own apiKeys.

**Comment by tmc** [comment]
Great suggestion -- can you open a PR implementing this?

**Comment by nidzola** [comment]
hey @tmc @heiningair  I've just created this PR https://github.com/tmc/langchaingo/pull/173 that address the issue above. If you could review! Thanks!

**Comment by tmc** [comment]
Thanks, closing.
