### ISSUE TITLE
add function call support

### ISSUE THREAD

**Issue by tmc** [tmc/langchaingo#162]

**Comment by kevin19930919** [comment]
Is this to support the new feature `function call` of the `chat completion api`?
If no one else has worked on this, I thought I could help.

**Comment by mfreeman451** [comment]
@kevin19930919 any progress on this? if not I might take a crack at it.. could use it

**Comment by kevin19930919** [comment]
@mfreeman451 Yes, I've done some development, maybe you can review it for me? This is my 1st time try to contribute to open source project, may need some help.

**Comment by mfreeman451** [comment]
It looks like this might not make sense at the moment since I think @tmc is going to just bring in a different openai client that already has this feature.

**Comment by kevin19930919** [comment]
Oh ok, so that means @tmc already made some progress on this?
