### ISSUE TITLE
Structured parser doesn't parse array

### ISSUE THREAD

**Issue by abdallamourad** [tmc/langchaingo#171]
Hi, I am trying to parse an array of data using structured parser. The json I am trying to parse is 
```json
{
  "ids": [number]
}
```

I am getting this error `map[] json: cannot unmarshal array into Go value of type string`
I tried to change the data type of the [parser](https://github.com/tmc/langchaingo/blob/main/outputparser/structured.go#L77) to map[string]any and it worked perfectly.

I was wondering if this case is handled somewhere else? Or can we add it to the existing parser?

**Comment by FluffyKebab** [comment]
The current structured parser only works with key value pairs of strings, but maybe the comma separated list output parser works for your case? Having a parser that can handle arbitrary JSON is definitely needed.

**Comment by abdallamourad** [comment]
Thank you @FluffyKebab for your response! 

I was wondering if this feature would benefit the project! I could probably pick it up?

**Comment by FluffyKebab** [comment]
Yes, please do! Here are some references from the other versions: [TS version](https://github.com/hwchase17/langchainjs/blob/main/langchain/src/output_parsers/structured.ts), [Python version](https://github.com/hwchase17/langchain/blob/master/langchain/output_parsers/pydantic.py). What do you think is the best golang version of a ZOD schema in the TS version and pydantic in the python version?

**Comment by navi504** [comment]
A PR was opened that used a better openai client and had the structure output parser, but it wasn't merged ontime and became dead 

The better openai client has a strictest output parser 
https://github.com/sashabaranov/go-openai/blob/1153eb2595d1529927757dd6df4de71faaafde02/jsonschema/json.go#L23C2-L23C2 

I also raised a similar issue if it's the right way to go
https://github.com/tmc/langchaingo/issues/197

**Comment by navicstein** [comment]
A PR was opened that used a better openai client and had the structure output parser, but it wasn't merged ontime and became dead 

The better openai client has a structured output parser 
https://github.com/sashabaranov/go-openai/blob/1153eb2595d1529927757dd6df4de71faaafde02/jsonschema/json.go#L23C2-L23C2 

I also raised a similar issue if it's the right way to go
https://github.com/tmc/langchaingo/issues/197

**Comment by dallman2** [comment]
The openai client that was targeted by the PR was what I was using before deciding to switch to langchain. I would definitely recommend finishing the PR, sasha's openai client is really nice to use.

**Comment by ewintr** [comment]
I hit this limit too and was wondering about what the best solution would me. I think the most efficient solution would not to use an external schema language Zod or JSON Schema, but instead rely on native struct tagging. That is, one would create a Go type and tag the fields, just like one always does. The output parser should then use that type as input for configuration and return a variable of that type as response.

**Comment by tmc** [comment]
Also a fan of aiming for a native struct but I'm open to suggested alternatives.

**Comment by xuning888** [comment]
+1

**Comment by lucaronca** [comment]
+1
