### ISSUE TITLE
feat: SimpleSequentialChain 

### ISSUE THREAD

**Issue by AMK9978** [tmc/langchaingo#181]
As shown in #61, we need to have a simple sequential chain feature, which enables people to interact with the LLM through a chain of prompts, and the output of each one is fed into the next. 
[source](https://github.com/hwchase17/langchain/blob/master/langchain/chains/sequential.py)

I'd like to work on it.
I'm creating this issue not to waste contributors' time, and get aligned.

**Comment by tobiade** [comment]
Hey @AMK9978, there's already #114 tracking this. I'm raising a PR shortly.

**Comment by AMK9978** [comment]
Okay! I'm waiting for your PR. I'll probably work on SequentialChain if you haven't implemented it already.

**Comment by tobiade** [comment]
Thanks @AMK9978 - `SequentialChain` was implemented too. See #183.
