### ISSUE TITLE
retrieval_qa discard ChainOption

### ISSUE THREAD

**Issue by leftfire** [tmc/langchaingo#189]
When I was using the RetrievalQA chain, I noticed that there was no streaming output. Upon inspection, I found that the Call function in the chains/retrieval_qa.go file was discarding the ChainOption. If there is a reason for this? I tried adding the ChainOption and passing it to the called function, and found that the streaming output started working properly.

chains/retrieval_qa.go
func (c RetrievalQA) Call(ctx context.Context, values map[string]any, _ ...ChainCallOption)

**Comment by FluffyKebab** [comment]
This is a mistake. A PR fixing this would be great.

**Comment by leftfire** [comment]
Sure. It's already been submitted. #190
