### ISSUE TITLE
Request new feature support

### ISSUE THREAD

**Issue by evoking6** [tmc/langchaingo#204]
Please consider adding a chain request message return for calculating token consumption

**Comment by evoking6** [comment]
I have added a field in the StreamingFunc function to accept the final request message content. But I don't think this implementation is reasonable. However, due to limited capabilities, I can't come up with a good solution for now, so I won't submit a PR
My modifications are here: https://github.com/tmc/langchaingo/commit/0b74d14536c63b592acaf0244a7483bad7a41b8c

**Comment by tmc** [comment]
Given the hooks exposed by the callback handler I think this need is met, please reopen if you feel otherwise.
