### ISSUE TITLE
[feature request] Set custom http client for OpenAI

### ISSUE THREAD

**Issue by akeemphilbert** [tmc/langchaingo#206]
- I am creating tests that don't make calls to the LLM by mocking the HTTP client. 
- The underlying openai client supports passing in an HTTP client as an option, but the wrapper around it does not (it hard codes the options passed in `openaiclient.New(options.token, options.model, options.baseURL, options.organization)` . 
- The Go Openai client also supports setting the client using `WithHTTPClient`, but to use this, the client on the LLM struct would need to be accessible. 

**Proposed Fix**
Make the openai client accessible with a getter `GetClient`

**Comment by KabudoWiseMan** [comment]
Hello there!

I've created a pr #223 with added public WithHTTPClient method for OpenAI, hope that suits your needs. Let me know if you have any feedback or suggestions

**Comment by JackBekket** [comment]
If I have local-ai node which runs at localhost:8000 and have API compatible with open-ai then I can create new langchain openai client which will use `localhost:8000` as baseURL?

**Comment by tmc** [comment]
Closing as this has merged.

@JackBekket yes, you can simply use the openai.WithBaseURL() option to override the base url.
