### ISSUE TITLE
Suggest implementation technology for documentation site

### ISSUE THREAD

**Issue by tmc** [tmc/langchaingo#21]
We should have a high quality rendered documentation site modeled after the existing langchain docs sites.

We need to determine what tool(s) to use and set up a CI pipeline to publish somewhere (probably github pages).

python langchain uses sphinx
typescript langchain uses docusaurus

I'm open to docusaurus but a go-based toolchain would be nice.

Shall we use Hugo?

**Comment by mfreeman451** [comment]
Going to set this up on something locally and get familiar https://gohugo.io/hosting-and-deployment/hosting-on-github/

**Comment by nguyenvanduocit** [comment]
Another tools is Vitepress, it's a is battery-included site generator for technical docs. take a look at : https://vitepress.dev/

**Comment by ChristianSch** [comment]
I think a go project lends itself for documentation in go without introducing another toolchain

**Comment by tmc** [comment]
We should use the best tool that gets us an experience like the other sites. I prefer a go based tool for sure but am not going to be dogmatic about it.

**Comment by ChristianSch** [comment]
Maybe we could clarify the needs beforehand. There are two different documentation areas I guess: the package API (godoc) and the "user guide". 

Additionally, something like this might be useful:
- https://github.com/robertkrimen/godocdown
- https://github.com/princjef/gomarkdoc

What I missed with hugo was a good documentation template but I just found this one: https://themes.gohugo.io/themes/doks/

**Comment by tmc** [comment]
I like https://themes.gohugo.io/themes/docsy/ but we'd need some theming to match the existing docs sites (https://python.langchain.com/en/latest/, https://js.langchain.com/docs/).

**Comment by deshetti** [comment]
@tmc My 2 cents.

Docusaurus is pretty straight forward and will match the docs site like here: https://js.langchain.com/docs/ as it seems like pretty much OOB theme.

The time would be well worth spending on implementing core features than having a customized theme IMO.

**Comment by tmc** [comment]
> @tmc My 2 cents.
> 
> Docusaurus is pretty straight forward and will match the docs site like here: https://js.langchain.com/docs/ as it seems like pretty much OOB theme.
> 
> The time would be well worth spending on implementing core features than having a customized theme IMO.
Yeah I've come to agree. Docusaurus it is!
