### ISSUE TITLE
Quick question: retrieve model name from a WithModel CallOption

### ISSUE THREAD

**Issue by cserpellZF** [tmc/langchaingo#219]
I am having a chain that receives a list of `CallOption` objects. For OpenAI models, one of them is created by `WithModel("...")`, that defines a model. Is there any way to extract the actual name of the model, so I can know which one will be called?

**Comment by tmc** [comment]
We don't currently expose a means of peeking at that currently. As the caller is providing it, there shouldn't be a barrier to knowing/recording which model is being used. Reopen this if you'd like but I don't think this needs to be an issue.
