### ISSUE TITLE
Potentially broken interaction with OpenAI when no functions are specified

### ISSUE THREAD

**Issue by KabudoWiseMan** [tmc/langchaingo#221]
Hello there!

I have recently upgraded to the latest version of the project, and it seems like [this PR](https://github.com/tmc/langchaingo/pull/215) might have introduced a disruption with OpenAI interaction when no functions are specified in a request. This issue is manifested when trying to run examples like openai-chat-example or other samples that don't have function specifications.

I'm persistently receiving an error:
`API returned unexpected status code: 400: None is not of type 'array' - 'functions'`

This occurs regardless of the behavior specified using llms.WithFunctionCallBehavior().

To further investigate, I attempted to make a direct curl request to OpenAI, specifying function_call as either "auto" or "none" (while not specifying any functions), for example:
```
curl https://api.openai.com/v1/chat/completions \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer <TOKEN>" \
  -d '{
    "model": "gpt-3.5-turbo",
    "messages": [{"role": "system", "content": "You are a helpful assistant."}, {"role": "user", "content": "Hello!"}],
    "function_call": "none"
  }'
```
And I received the following error:
```
{
  "error": {
    "message": "Invalid value for 'function_call': 'function_call' is only allowed when 'functions' are specified.",
    "type": "invalid_request_error",
    "param": "function_call",
    "code": null
  }
}
```

This leads me to believe that the default behaviour should be not to include "function_call" field to the request at all if it's not specified directly with llms.WithFunctionCallBehavior()

**Comment by tmc** [comment]
😵‍💫 you're very right. Fix pushed, this certainly should have been caught in CI, and we can expand tests to do so.
