### ISSUE TITLE
chains.WithStreamingFunc does not work

### ISSUE THREAD

**Issue by DeerShark** [tmc/langchaingo#232]
When I use `llm, err := openai.NewChat()` and `llms.WithStreamingFunc`, it works, can stream output.

But when I use `chains.WithStreamingFunc` in `chains.Call`, there is no output, it seems that this function is not called?

```go
func Ask(input string) (map[string]any, error) {

	llm, err := openai.New()
	if err != nil {
		return nil, err
	}

	...

	return chains.Call(context.Background(), sequentialChain, map[string]any{"title": "Tragedy at sunset on the beach", "era": "Victorian"}, chains.WithStreamingFunc(func(ctx context.Context, chunk []byte) error {
		fmt.Print(string(chunk))
		return nil
	}))
```

**Comment by tmc** [comment]
This sounds like a bug. One aspect here is that if/when you have an OutputParser the intermediate values may not be that useful (though we could consider incremental output parsing).

**Comment by tmc** [comment]
Fixed by 266
