### ISSUE TITLE
sql error : converting NULL to string is unsupported

### ISSUE THREAD

**Issue by felixgunawan** [tmc/langchaingo#235]
When trying out sql chain using some tables with nullable columns, chains.Predict will return error when trying to query the database
```
sql: Scan error on column index 2, name \"category_id\": converting NULL to string is unsupported
```

fix suggestion: https://github.com/tmc/langchaingo/pull/234

**Comment by malnick** [comment]
I started a [fix](https://github.com/tmc/langchaingo/compare/main...malnick:langchaingo:testing) for this last Friday, let me know if you need any help on #234

**Comment by felixgunawan** [comment]
thanks, can you help to review it?
