### ISSUE TITLE
Model is not properly set for Azure OpenAI if using `llm.Call` and not setting Model in Client

### ISSUE THREAD

**Issue by amcode21** [tmc/langchaingo#244]
In `openaiclient.go` in the `llms/openai/internal/openaiclient` directory, there is this code:

```go
// CreateChat creates chat request.
func (c *Client) CreateChat(ctx context.Context, r *ChatRequest) (*ChatResponse, error) {
	if r.Model == "" {
		if c.Model == "" {
			r.Model = defaultChatModel
		} else {
			r.Model = c.Model
		}
	}
	if r.FunctionCallBehavior == "" && len(r.Functions) > 0 {
		r.FunctionCallBehavior = defaultFunctionCallBehavior
	}
	resp, err := c.createChat(ctx, r)
```

In the `createChat` function, `c.buildURL` is called, which then calls `c.buildAzureURL` if the `APIType` is Azure or AzureAD, however the model is not passed to `c.buildURL`, so it references `c.Model`, as shown below:

```go
func (c *Client) buildAzureURL(suffix string) string {
	baseURL := c.baseURL
	baseURL = strings.TrimRight(baseURL, "/")

	// azure example url:
	// /openai/deployments/{model}/chat/completions?api-version={api_version}
	return fmt.Sprintf("%s/openai/deployments/%s%s?api-version=%s",
		baseURL, c.Model, suffix, c.apiVersion,
	)
}
```

This code leaves the model ID blank if it is only provided in the `llm.Call` function as an option, since `c.Model` is never changed, nor is the model ID passed to `c.buildAzureURL`.

**Comment by zivkovicn** [comment]
This should have been fixed now. With the latest updated in the code base for the azure part.
