### ISSUE TITLE
feature: Huggingface hub embedder 

### ISSUE THREAD

**Issue by zivkovicn** [tmc/langchaingo#245]
## Description
- we should have Huggingface hub embedder, like we currently have for openai/veretexai.

I will work on this.

**Comment by nidzola** [comment]
created: https://github.com/tmc/langchaingo/pull/246

**Comment by KarimNMG** [comment]
@nidzola I am trying to use the huggingface embedder, but it's not stable sometimes it works fine, sometimes I am getting this error "API returned unexpected status code: 503: unable to create embeddings", Could you please explain why this happen?

**Comment by zivkovicn** [comment]
@KarimNMG that is the Huggingface API issue - has nothing to do with the embedder it self. That usually means the instance is spinning up for you and should resolve after a while and [this](https://huggingface.co/docs/api-inference/faq#:~:text=Rate%20limits&text=We%20try%20to%20balance%20the,errors%20saying%20models%20are%20loading.).

**Comment by KarimNMG** [comment]
@zivkovicn Thanks for your fast response !. Is there a way to load the model once and use it like python?

**Comment by zivkovicn** [comment]
@KarimNMG probably, but that would require some package like `SentenceTransformer` that python has.

**Comment by KarimNMG** [comment]
Ok, Thank you
