### ISSUE TITLE
[Feature Request] able to use chromadb as the vector stores

### ISSUE THREAD

**Issue by bjwswang** [tmc/langchaingo#278]
We would like to use `chormadb(https://github.com/chroma-core/chroma)` as our vector store in langchaingo. Any plans on this feature ? If we do have a plan, I would like to work on this feature.

**Comment by noodnik2** [comment]
FYI I'm working on a PR to add remote Chroma support (i.e., not in-process, but by accessing a remote Chromadb service).  If all goes well, expect an initial implementation for review later this week.

**Comment by bjwswang** [comment]
> FYI I'm working on a PR to add remote Chroma support (i.e., not in-process, but by accessing a remote Chromadb service).  If all goes well, expect an initial implementation for review later this week.

well... i think we should contrubute to  chroma-go  before Introduce it into this project

**Comment by bjwswang** [comment]
close this issue since this is merged
