### ISSUE TITLE
Langchaingo vs Native Langchain in Python

### ISSUE THREAD

**Issue by atreyamj** [tmc/langchaingo#304]
Hi there,
Thank you so much for this amazing Go translation for LangChain. We were exploring building LangChain based LLM Apps and were exploring use LangChainGo as opposed to the Native Py LangChain. 

On that lines, I was wondering if there was any link or document explaining the feature parity between LangChainGo vs LangChain Python?

Also how do LangChain Integrations work with LangChainGo ?

Thank You!

**Comment by FluffyKebab** [comment]
Here is the parity matrix: https://github.com/tmc/langchaingo/blob/main/docs/parity_matrix.md.

**Comment by atreyamj** [comment]
Perfect ! This is really helpful! Thank you so much
