### ISSUE TITLE
[Urgent Feature Request] Return vector id from Pinecone

### ISSUE THREAD

**Issue by shrikarnag-q** [tmc/langchaingo#306]
While using 

err = store.AddDocuments(context.Background(), []schema.Document{
        {
            PageContent: userData,
            Metadata: map[string]any{

            },
        },
    })
    
Please return pinecone vector id

Something like

id, err := store.AddDocuments(context.Background(), []schema.Document{
        {
            PageContent: userData,
            Metadata: map[string]any{

            },
        },
    })
    
    if err != nil {
		log.Fatal(err)
	}
	
This is very important to do update or delete vector from pinecone for which we can use other library. 
Help needed here urgently, stuck in a project.

**Comment by tmc** [comment]
Sorry to hear that you're in a bit of a bind. Please feel free to open a PR suggesting the edit you'd like, in the mean time you can fork the code and use go.work files to replace your implementation.
