### ISSUE TITLE
Add Ollama support

### ISSUE THREAD

**Issue by tmc** [tmc/langchaingo#307]
We should have Ollama support.

https://github.com/jmorganca/ollama/blob/main/docs/api.md

**Comment by bjwswang** [comment]
@tmc This is so cool! Seems this is a pure go llm runner.

**Comment by bjwswang** [comment]
@tmc I am interested in this . /assign @bjwswang

**Comment by CyrilPeponnet** [comment]
I started toy around here https://github.com/tmc/langchaingo/pull/327

**Comment by sausheong** [comment]
Exciting! Can't wait to use it!

**Comment by tmc** [comment]
Closed via #327 ! Announced here: https://twitter.com/traviscline/status/1718400239441420391?s=61&t=mAFtj7oJZmLZnH-5yXho9w
