### ISSUE TITLE
How to use Azure Source?

### ISSUE THREAD

**Issue by Prayforhanluo** [tmc/langchaingo#328]
Hello, I want to use langchain-go to build LLM application. I have serveral questions here:
1. How to use Azure Source? Especially how to specify the engine name of Azure resource
my code here:

            err := os.Setenv("OPENAI_API_KEY", "xxxx")
            if err != nil {
            fmt.Println(1)
            panic(err)
            }
            err = os.Setenv("OPENAI_BASE_URL", "xxxx")
            if err != nil {
            fmt.Println(2)
            panic(err)
            }
            model, err := openai.New(openai.WithModel("gpt-4"))
            if err != nil {
            fmt.Println(3)
            panic(err)
            }
            prompt := prompts.NewPromptTemplate(
            "What is the capital of {{.country}}",
            []string{"country"},
            )
            
            chain := chains.NewLLMChain(model, prompt)
            result, err := chains.Predict(context.Background(),
            chain, map[string]interface{}{
	            "country": "China",
            },
            )
            if err != nil {
            fmt.Println(4)
            panic(err)
            }
            fmt.Println(result)

It returns 404 Resource not found. But in my python code this resource works.

2. If I need to change resource, I need to run os.Setenv every time, Any other way to do it.?
3. How to use proxy? can I use a custom http client, Is there any example code？

Maybe there are corresponding answers to these questions, but I didn't find them in the example.

Thanks for any helpful information!

**Comment by caxqueiroz** [comment]
snippet code for using azure. 

llm, err := openai.New(openai.WithToken(viper.GetString("OPENAI_API_KEY")),
		openai.WithAPIType(openai.APITypeAzure),
		openai.WithAPIVersion(viper.GetString("OPEN_AI_API_VERSION")),
		openai.WithBaseURL(viper.GetString("OPEN_AI_URL")),
		openai.WithModel(viper.GetString("OPEN_AI_MODEL")),
		openai.WithEmbeddingModel(viper.GetString("OPEN_AI_EMBEDDING_MODEL")))

for using proxy:

proxy, err := url.Parse("proxy addr")
		if err != nil {
			return nil, err
		}
		transport := &http.Transport{
			Proxy: http.ProxyURL(proxy),
		}

		httpClient := &http.Client{
			Transport: transport,
		}
 then, use 
openai.WithHTTPClient(httpClient)

**Comment by Prayforhanluo** [comment]
> chain := chains.NewLLMChain(model, prompt)
>      result, err := chains.Predict(context.Background(),
>      chain, map[string]interface{}{
>          "country": "China",
>      },
>      )

Thanks a lot.

**Comment by Prayforhanluo** [comment]
Thanks a lot~
