### ISSUE TITLE
Different embedding results from EmbedQuery vs EmbedDocuments

### ISSUE THREAD

**Issue by eliben** [tmc/langchaingo#356]
This sample (using a locally running Ollama):

```go
package main

import (
	"context"
	"fmt"
	"log"

	ollama_emb "github.com/tmc/langchaingo/embeddings/ollama"
	"github.com/tmc/langchaingo/llms/ollama"
)

func main() {
	ctx := context.Background()
	ollamaLLM, err := ollama.New(ollama.WithModel("llama2"))
	if err != nil {
		log.Fatal(err)
	}
	ollamaEmbeder, err := ollama_emb.NewOllama(ollama_emb.WithClient(*ollamaLLM))
	if err != nil {
		log.Fatal(err)
	}

	vec, err := ollamaEmbeder.EmbedQuery(ctx, "some text")
	if err != nil {
		panic(err)
	}

	fmt.Println("for single embedding:")
	fmt.Println(len(vec), "items")
	fmt.Println("first few:", vec[:16])

	texts := []string{
		"some text",
		"some other text",
		"nothing to see here",
		"some text",
	}
	vecs, err := ollamaEmbeder.EmbedDocuments(ctx, texts)
	if err != nil {
		panic(err)
	}

	fmt.Printf("got %d embeddings\n", len(vecs))
	for i, v := range vecs {
		fmt.Printf("[%d] len=%v, first few: %v\n", i, len(v), v[:16])
	}
}
```

I get the result:

```
for single embedding:
4096 items
first few: [-0.29370144 -0.9472216 0.15928172 2.9431767 2.1008253 0.42557585 0.4646868 -1.2639807 0.74785733 2.0149763 0.06937195 1.9570599 1.0287265 -0.59564227 0.4246622 0.55052483]
got 4 embeddings
[0] len=4096, first few: [-0.0023840654 -0.0076888897 0.001292939 0.023890676 0.017053049 0.0034545308 0.0037720064 -0.010260123 0.006070589 0.016356185 0.0005631136 0.015886059 0.008350491 -0.0048350124 0.0034471143 0.00446878]
[1] len=4096, first few: [0.00018647342 -0.0074219094 -0.0017224154 0.024820441 0.018676626 0.009781131 0.0017315162 -0.009649557 0.002851611 0.017244304 -0.003103958 0.01625366 0.0053226543 -0.0037721072 -0.0015953793 0.0027238138]
[2] len=4096, first few: [0.02413346 -0.004885593 0.020026844 0.010123044 -0.017859628 -0.02488833 0.004874667 -0.020612739 0.014844988 0.004664329 -0.009499503 -0.012011117 0.026116962 0.022425374 -0.010794117 -0.005852883]
[3] len=4096, first few: [-0.0023840654 -0.0076888897 0.001292939 0.023890676 0.017053049 0.0034545308 0.0037720064 -0.010260123 0.006070589 0.016356185 0.0005631136 0.015886059 0.008350491 -0.0048350124 0.0034471143 0.00446878]
```

Note that the same string `"some text"` gets a very different embedding vector when embedded via `EmbedQuery` vs. `EmbedDocuments` - this is a surprising result; I'd expect them to be the same

Looking at the code, this could be the result of applying `CombineVectors` to the latter, but still - shouldn't we get the same result?

**Comment by eliben** [comment]
Taking the OpenAI embedded as an example, langchaingo seems to implement embeddings differently from langchain (py), and it's not clear to me why this is so.

[In langchain (py)](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/embeddings/openai.py), `embed_query` just invokes `embed_documents` with a single text:

```python
    def embed_query(self, text: str) -> List[float]:
        return self.embed_documents([text])[0]
```

Whereas in [langchaingo](https://github.com/tmc/langchaingo/blob/09a09b3b60936669bcf723c90c11c9b480039c87/embeddings/openai/openai.go), `EmbedQuery` simply calls `e.client.CreateEmbedding(ctx, []string{text})`, but `EmbedDocuments` does something much more complicated:

1. Batches the texts
2. Runs `e.client.CreateEmbedding(ctx, texts)` on each batch
3. Calculates lengths and "combines" the result vectors weighted by text length

Why the difference? Why doesn't langchaingo follow the simpler behavior of langchain (py)?

**Comment by eliben** [comment]
After debugging for a bit, the issue here is that in `EmbedDocuments`, `CombineVectors` gets called all the time, even if batch size is 1. `CombineVectors` normalizes its result, so the outcome is different from `EmbedQuery`.

A simple fix would be to avoid invoking `CombineVectors` when the batch size is 1 - because there should be nothing to combine.

@tmc WDYT?

**Comment by tmc** [comment]
> After debugging for a bit, the issue here is that in `EmbedDocuments`, `CombineVectors` gets called all the time, even if batch size is 1. `CombineVectors` normalizes its result, so the outcome is different from `EmbedQuery`.
> 
> A simple fix would be to avoid invoking `CombineVectors` when the batch size is 1 - because there should be nothing to combine.
> 
> @tmc WDYT?

That sounds right to me -- can you open a PR? I've been pretty tied up with $dayjob recently, sorry about the delay here.

**Comment by eliben** [comment]
> > After debugging for a bit, the issue here is that in `EmbedDocuments`, `CombineVectors` gets called all the time, even if batch size is 1. `CombineVectors` normalizes its result, so the outcome is different from `EmbedQuery`.
> > A simple fix would be to avoid invoking `CombineVectors` when the batch size is 1 - because there should be nothing to combine.
> > @tmc WDYT?
> 
> That sounds right to me -- can you open a PR? I've been pretty tied up with $dayjob recently, sorry about the delay here.

Sent #357 for Openai.

Once that's accepted, I can look into fixing it for the other LLMs as well. There's a lot of code that may be worthwhile to factor out, but that feels like a separate PR from the fix.
