### ISSUE TITLE
Remove large unused binary file at repo root?

### ISSUE THREAD

**Issue by eliben** [tmc/langchaingo#389]
There's a 15 MiB binary file named `chroma_vectorstore_example` at the repository's root that appears to be unused. It comes from https://github.com/tmc/langchaingo/pull/282 -- I left a comment there a while ago, but got no reply.

I propose removing this file; any concerns?

**Comment by tmc** [comment]
No concerns, added in error.

**Comment by eliben** [comment]
Removed.

Note that this file is still in the Git history of the project and full clones will continue being a bit slower. What other projects typically do is do a git history rewrite to remove the mistakenly committed file from all commits. This requires a force push though, and can't be made in a PR.

Travis, you may be able to do this if you want.

**Comment by tmc** [comment]
I went ahead and rebased and force pushed as there was other binary content accidentally included.

**Comment by noodnik2** [comment]
Oops; sorry about that!  I'll try to pay more attention to files added in future PRs.  Thanks for the clean-up!
