### ISSUE TITLE
Support  LLM Caching

### ISSUE THREAD

**Issue by fatedier** [tmc/langchaingo#395]
https://python.langchain.com/docs/modules/model_io/llms/llm_caching

**Comment by corani** [comment]
@tmc / @eliben I was thinking about two possible APIs for this:

```go
// (1) as an `Option` to each LLM implementation
llm, _ := ollama.New(
    llms.WithCache(inmemory.New()),
)

// (2) as a wrapper
var llm llms.Model

llm, _ = ollama.New()
llm, _ = llms.WithCache(llm, inmemory.New())
```

To avoid having to reimplement this in every implementation my preference would be (2), but please share your thoughts on this. This seems like something I could kick off with an initial in-memory backend. Idea would be to create an interface for the backend, so additional backends (like sqlite, redis, etc.) can be added later on.

**Comment by tmc** [comment]
Supportive of not having to touch each model impl.
