### ISSUE TITLE
pgvector DropTables() fails because collectionTable dropped before embeddingTable

### ISSUE THREAD

**Issue by mehulmshah** [tmc/langchaingo#440]
The pgvector vectorstore has a `DropTables(ctx)` function that drops the `collectionTableName` Table, and then drops the `embeddingTable` Table.

Running this function causes the error:
```ERROR: cannot drop table "Collections" because other objects depend on it (SQLSTATE 2BP01)```

In order to resolve this, you simply have to change the order of dropping so that the `embeddingTableName` Table is dropped first.

i.e. Simply change the function to this:
```
	if _, err := s.conn.Exec(ctx, fmt.Sprintf(`DROP TABLE IF EXISTS %s`, s.embeddingTableName)); err != nil {
		return err
	}
	if _, err := s.conn.Exec(ctx, fmt.Sprintf(`DROP TABLE IF EXISTS %s`, s.collectionTableName)); err != nil {
		return err
	}

	return nil
```

**Comment by tmc** [comment]
Fixed in #441
