### ISSUE TITLE
Why go langchain?

### ISSUE THREAD

**Issue by GingerMoon** [tmc/langchaingo#452]
Hi @tmc , thanks for making this awesome golang langchain.
I am hesitating to choose which framework to use, a go version or a python version.
Is the only reason why we choose a golang framework because it's more friendly to gophers?
Are there any other reasons for choosing a golang framework?
Any insight would be much appreciated!

**Comment by tmc** [comment]
This project is positioned to be a more production-friendly environment to host these workloads. Python is great for development and training but after years of trying to get it working well in production I have moved to put workloads that have stringent reliability and performance requirements into Go. I'll take note that we should explain how this project is positioned in the outward facing documentation. I'm going to close this but feel free to continue the conversation!

**Comment by GingerMoon** [comment]
Hi @tmc , thanks for the reply. 
I am trying to pursuade other team mates to use the go version. So I would be very appreciate if you could just share some concrete/real problems (which exists python langchain) solved by o langchain.
Thans a lot in advance!

**Comment by bjwswang** [comment]
Hi @GingerMoon . From my point of view, langchaingo is much more `CloudNative` which can be easily integrated into kubernetes ecosystem . 

Actually we are using both langchaingo and langchain(python) in our project.
- langchaingo : cloud natvie integration
- langchain:  data processing before building RAG applications.
