### ISSUE TITLE
vectorstores should return score in document when run SimilaritySearch functions.

### ISSUE THREAD

**Issue by Abirdcfly** [tmc/langchaingo#456]
Other vectorstores's `SimilaritySearch` functions all return the document's score value:
- milvus add score in https://github.com/tmc/langchaingo/blob/351b8b52b1bf85a2aab82f6e626468e905e9d662/vectorstores/milvus/milvus.go#L279
- pgvector in https://github.com/tmc/langchaingo/blob/351b8b52b1bf85a2aab82f6e626468e905e9d662/vectorstores/pgvector/pgvector.go#L260
- pinecone in https://github.com/tmc/langchaingo/blob/351b8b52b1bf85a2aab82f6e626468e905e9d662/vectorstores/pinecone/restapi.go#L170

weaviate: https://github.com/tmc/langchaingo/pull/454
chroma: https://github.com/tmc/langchaingo/pull/449

**Comment by tmc** [comment]
Agreed.

**Comment by tmc** [comment]
Closing as those are merged.
