### ISSUE TITLE
Refactor LLM interfaces to prepare for multi-modal models

### ISSUE THREAD

**Issue by eliben** [tmc/langchaingo#465]
(discussion started in #410 and email)

----

I started looking at the chat vs. non-chat interfaces, beginning with OpenAI. These days, all OpenAI API calls are supposed to go through the chat endpoint -- see https://platform.openai.com/docs/guides/text-generation (the old non-chat endpoints are just for legacy models).

We can remove duplication stemming from these interfaces having overlapping but incompatible signatures:

```go
// LLM is a langchaingo Large Language Model.
type LLM interface {
    Call(ctx context.Context, prompt string, options ...CallOption) (string, error)
    Generate(ctx context.Context, prompts []string, options ...CallOption) ([]*Generation, error)
}

// ChatLLM is a langchaingo LLM that can be used for chatting.
type ChatLLM interface {
    Call(ctx context.Context, messages []schema.ChatMessage, options ...CallOption) (*schema.AIChatMessage, error)
    Generate(ctx context.Context, messages [][]schema.ChatMessage, options ...CallOption) ([]*Generation, error)
}
```

As it is right now, a single type can't implement both, so everything is duplicated. Also, the LLM interface is unsuitable for multi-modals because it takes a string. This may require quite a bit of breaking interfaces, unfortunately.

**Comment by eliben** [comment]
There's another interface that seems related, with a somewhat similar signature:

```go
// LanguageModel is the interface all language models must implement.
type LanguageModel interface {
	// Take in a list of prompt values and return an LLMResult.
	GeneratePrompt(ctx context.Context, prompts []schema.PromptValue, options ...CallOption) (LLMResult, error)
	// Get the number of tokens present in the text.
	GetNumTokens(text string) int
}
```

Unless I'm mistaken, it seems to only be used in in `chains`.

**Comment by eliben** [comment]
The idea of the main refactoring is to create a new interface for multimodal LLMs, with a single method, name TBD (could be `Complete` or `Call` or `Generate`, etc). The name of the interface is TBD as well (could be `LLM`, or `MultiModal` or maybe just `Model`?)

Looking at some of the backends that will end up being the most popular:

1. OpenAI: [the API](https://platform.openai.com/docs/guides/text-generation/chat-completions-api) takes an array of messages, each one with a role and an option type that can specify text an image (as a URL).
2. Ollama: [the API](https://github.com/jmorganca/ollama/blob/main/docs/api.md#generate-a-completion) currently takes a single text prompt, but potentially an array of accompanying images, base64-encoded
3. Google's new generative AI: [the SDK](https://pkg.go.dev/github.com/google/generative-ai-go@v0.5.0/genai#GenerativeModel.GenerateContent) takes a slice of "parts", each part can be a text message or a binary blob (for images) etc.

All these can potentially be extended in the future with additional types of messages (videos, etc), and all are also (theoretically) able to return a sequence of multi-typed responses.

Therefore, the main interface should look something like this (once again, names TBD):

```go
type Model interface {
  GenerateContent(ctx context.Context, params []*Param, options ...CallOption) (*Response, error)
}
```

Chat interfaces and various convenience wrapper (e.g. extract only the first response from a call, or some simple param combinations) can be built on top of this interace.

The work plan should be:

1. First define the interface and implement this method for all current LLMs; for the common ones we can implement it, for the more obscure ones we can just use it to call another underlying method for now and leave it to implementers to complete.
2. Implement chat on top of this new interface
3. Remove the existing `LLM` and `ChatLLM` interfaces. If we decide to name the new interface or its method in a way that conflicts with existing interfaces, we can give it a temporary name while working on the refactoring and then rename it after these are removed.

@tmc LMK what you think about this plan, and the naming. For naming, the names in the sample above seem good to me (`Model` for interface and `GenerateContent` for the method) because they clearly convey the goal and don't conflict with current methods/interfaces, which will make the transition easier. But I don't feel strongly about naming.

**Comment by tmc** [comment]
That plan sounds sensible to me and I'm comfortable with that proposed interface.

**Comment by eliben** [comment]
Update: the `Model` interface can now cover pretty much everything `LLM` and `ChatLLM` can, plus more (multi-modal inputs!)

One thing that's missing is functions support; that said, functions are currently deprecated in OpenAI - tools is the new way (#507)

**Comment by eliben** [comment]
Building on all the work in this issue, https://github.com/tmc/langchaingo/pull/521 is the big PR to finalize the refactoring (*)

The main interface to LLMs is now:

```go
type Model interface {
	// Call is a simplified interface for Model, generating a single string
	// response from a single string prompt.
	//
	// It is here for backwards compatibility only and may be removed in the
	// future; please use GenerateContent instead.
	Call(ctx context.Context, prompt string, options ...CallOption) (string, error)

	// GenerateContent asks the model to generate content from a sequence of
	// messages. It's the most general interface for LLMs that support chat-like
	// interactions.
	GenerateContent(ctx context.Context, messages []MessageContent, options ...CallOption) (*ContentResponse, error)
}
```

The `Call` method is left for backwards compatibility so we don't break too many clients early on.

I recommend releasing a new version of langchaingo once this lands and then updating the examples to use `GenerateContent` directly. In a later release we can remove the legacy `Call` method



(*) minus some small cleanups that will follow up later
