### ISSUE TITLE
Add doc.go files to every package.

### ISSUE THREAD

**Issue by tmc** [tmc/langchaingo#5]
Every package should have a well written package-level comment beginning with "// Package (packagename)".

**Comment by teezzan** [comment]
@tmc, can I hop on this? Looks like something I can start with while getting to know the codebase for more contributions.

**Comment by tmc** [comment]
> @tmc, can I hop on this? Looks like something I can start with while getting to know the codebase for more contributions.

@teezzan Yes please do!
