### ISSUE TITLE
How's the progress going with support for multimodal models?

### ISSUE THREAD

**Issue by Seumi** [tmc/langchaingo#510]
I saw that branch [gpt4-vision-support](https://github.com/tmc/langchaingo/tree/gpt4-vision-support) is working on supporting GPT4V, and it seems that the ChatMessage schema has added ContentPartList. This work could be helpful for other models, so what's the status now, and when will it be merged into the main branch? Thx :)

**Comment by tmc** [comment]
Coming very soon, the refactor of the core Model interface is/was an important step for this.

**Comment by eliben** [comment]
See https://github.com/tmc/langchaingo/issues/465
