### ISSUE TITLE
Run integration tests for the database layer (Mysql & Postgres) using testcontainers-go

### ISSUE THREAD

**Issue by mdelapenya** [tmc/langchaingo#517]
Hi from the testcontainers community! 👋  I'm the core maintainer of https://github.com/testcontainers/testcontainers-go, and I'd like to contribute a tiny improvement regarding the current integration test suite.

I've noted the MySQL and Postgres tests are not run in the CI, or at least I've not found how apart from manually setting the right env var - e.g. `LANGCHAINGO_TEST_MYSQL`, and wanted to replicate what the langchain4j project did (please see https://github.com/langchain4j/langchain4j/pulls?q=is%3Apr+testcontainers+is%3Aclosed)

I see mysql and postgres stores tests as a super quick-win to add tests for, and I wonder if you would be interested in running those tests for them for every PR/merge, of course at the cost of seconds, which is what it takes to spin the right Docker container for each data store.

I leave here the link to our docs site in the case you are interested in understanding more about our proposition to run integration tests with real dependencies:
- https://golang.testcontainers.org
- https://www.testcontainers.org

Please let me know if you want to know more about the project, I'm open to any collaboration.

Cheers!

**Comment by mdelapenya** [comment]
An example run of my eventual proposal, using `mysql:8` and `postgres:13` as target data stores, would be:

https://github.com/tmc/langchaingo/assets/951580/318302cd-3eb8-40f3-bc24-aad7812a1567

For this example, both Docker images are already pulled in my local machine, as for a CI worker it would be fast to pull them (or even use a GH action cache for them)

**Comment by tmc** [comment]
Yeah we should either do that or use ory/dockertest.

**Comment by mdelapenya** [comment]
Do you already have a preference, or want me to submit a draft pr so you can evaluate it?
