### ISSUE TITLE
vectorstores: add redis

### ISSUE THREAD

**Issue by h0rv** [tmc/langchaingo#581]
It would be great to add Redis with RedisSearch (https://github.com/RediSearch/RediSearch) support. 

There is a Go client (https://github.com/redis/rueidis) that has API support for the RedisSearch commands. This package also supports RedisJSON, which is a good combo with RedisSearch.

Redis Stack supports both RedisSearch and RedisJSON (https://redis.io/docs/about/about-stack/). Image: https://hub.docker.com/r/redis/redis-stack.

**Comment by 0x090909** [comment]
Yess I agree

**Comment by tmc** [comment]
@h0rv would love to see this -- can you tackle it?

**Comment by tmc** [comment]
I believe this is addressed in #777
