### ISSUE TITLE
integrate with milvus for vector-store

### ISSUE THREAD

**Issue by zach030** [tmc/langchaingo#59]
https://github.com/milvus-io/milvus-sdk-go

**Comment by obitech** [comment]
I would like to look into this 👋 
@tmc would it make sense to create an `example/` dir (or something like that) with a `docker-compose.yaml` and `main.go` showcasing this, locally?

**Comment by pattonjp** [comment]
I had started working on this for a side project before finding this issue. I have a fork [here](https://github.com/pattonjp/langchaingo/tree/milvus) if anyone finds interesting i can create a pr after some more testing.
