### ISSUE TITLE
pgvector `WithEmbeddingTableName` sanitization conflicts with index creation 

### ISSUE THREAD

**Issue by rajaiswal** [tmc/langchaingo#605]
When I initialize pgvector like this:
```go
pgv, err := pgvector.New(
                ...
		pgvector.WithEmbeddingTableName("custom_name"),
	)
```
The `WithEmbeddingTableName` sanitizes the input and its value becomes `"\"custom_name\""`, which is set on `Store.embeddingTableName`.
This then raises an error when the `init` method is called and it tries to create an index:
```go
sql = fmt.Sprintf(`CREATE INDEX IF NOT EXISTS %s_collection_id ON %s (collection_id)`, s.embeddingTableName, s.embeddingTableName)
```
The generated error is:
```
ERROR: syntax error at or near "_collection_id" (SQLSTATE 42601)
```
I believe we could do away with the sanitization part in `WithEmbeddingTableName`

**Comment by nkwangleiGIT** [comment]
@Abirdcfly I think we can remove the sanitization logic for WithEmbeddingTableName, pls help confirm as the table name might be schema.table_name

**Comment by Abirdcfly** [comment]
Why use https://pkg.go.dev/github.com/jackc/pgx#Identifier.Sanitize, the relevant context is here: https://github.com/tmc/langchaingo/pull/377#discussion_r1415287088

IMO, Modify the `CREATE INDEX` statement or deprecate `Sanitize()` are both acceptable.

cc @tmc @eliben
