### ISSUE TITLE
Feature Parity Matrix

### ISSUE THREAD

**Issue by tmc** [tmc/langchaingo#61]
We should take inspiration (and content) from https://langchain.com/features.html and have a markdown file that indicates the current implementation state.

Once we have docs site (#21) this content could go there.

**Comment by rdbell** [comment]
**LangChain Go Features**

**Feature** | **Status**
-- | --
Prompt Templates | ✅
Few Shot Prompt Template | ✅
Output Parsers | ✅
Example Selectors | ✅

**Text Splitters**  
**Feature** | **Status**
-- | --
Character Text Splitter | ✅
Recursive Character Text Splitter | ✅
Markdown Text Splitter | ✅

**Chains**  
**Feature** | **Status**
-- | --
LLM Chain | ✅
Stuff Combine Documents Chain | ✅
Map Reduce Combine Documents Chain | ✅
Refine Combine Documents Chain | ✅
Map Rerank Combine Documents Chain | ❌
Chat Vector DB Chain | ✅
Vector DB QA Chain | ✅
Analyze Document Chain | ✅
Question Answering Chains | ✅
Summarization Chains | ✅
Question Answering With Sources Chains | ❌
SQL Database Chain | ✅
API Chain | ❌
Transformation Chain | ❌
Constitutional Chain | ❌
Conversational Chain | ✅
Graph QA Chain | ❌
HyDE Chain | ❌
LLM Bash Chain | ❌
LLM Math Chain | ❌
PAL Chain | ❌
LLM Requests Chain | ❌
Moderation Chain | ❌
Sequential Chain | ❌
Simple Sequential Chain | ❌

**Agents**
**Feature** | **Status**
-- | --
zero-shot-react-description | ✅
chat-zero-shot-react-description | ✅
self-ask-with-search | ❌
react-docstore | ❌
conversational-react-description | ❌
chat-conversational-react-description | ✅

**Memory**
**Feature** | **Status**
-- | --
Buffer Memory | ✅
Buffer Window Meory | ✅
Summary Memory | ❌
Entity Memory | ❌
Summary Buffer Memory | ❌
Knowledge Graph Memory | ❌

**Comment by tmc** [comment]
Awesome thank you @rdbell -- can you open a PR with this content in a markdown file? (you can just place it in ./docs in the root for now).

Also, please join the #langchain-go Discord channel in the langchain discord.

**Comment by MarkEdmondson1234** [comment]
May I ask if langchain.vectorstores.chroma should also be in this list, or is that implied in "Chat Vector DB Chain"?  And When its ticked done, is that when its in the "exp" folder or needs to be moved out once complete?  Just feeling out to see if I can contribute anywhere, and this is a handy grid to assess :)

**Comment by tmc** [comment]
> May I ask if langchain.vectorstores.chroma should also be in this list, or is that implied in "Chat Vector DB Chain"? And When its ticked done, is that when its in the "exp" folder or needs to be moved out once complete? Just feeling out to see if I can contribute anywhere, and this is a handy grid to assess :)

I think we can have green checks and "(exp)" for implementations in exp.

**Comment by princejha95** [comment]
Hi, can i grab this issue ?
