### ISSUE TITLE
 What is the correct approach to implement image generation in langchaingo??

### ISSUE THREAD

**Issue by devinyf** [tmc/langchaingo#611]
Hi~ Currently I want to implementing a text2image generation API function in my forked branch to do some test, but I'm confused about something:
The text2image API using the same ApiKey with the llm model,  just like chatgpt and Dall-E.

And I found the python version like this:
https://python.langchain.com/docs/integrations/tools/dalle_image_generator
```python
from langchain_community.utilities.dalle_image_generator import DallEAPIWrapper

image_url = DallEAPIWrapper().run(chain.run("halloween night at a haunted museum"))
```

But after #465, we already have content types(TextPart, BinaryPart, ImageURLPart) in llms,
what I want to know is, should we implement image generation  just in llms package?
for example: implementing  Dall-E3 API call  inside the  llms -->  openaiclient  ??

Or we should still followed the python version, implement it as a tools like DallEAPIWrapper??
(may have to support other functions in future, like speech2text, video2text...)

Which is the correct approach in langchaingo??

Thanks

**Comment by bjwswang** [comment]
It's a good idea to make it a tool.

**Comment by devalexandre** [comment]
I'was thinking aout, but can't inside llm , because is only openai after end whipers , I get it for work :)

**Comment by devinyf** [comment]
I choice to use tool, and It worked well for me
