### ISSUE TITLE
[feature request] Tool should support multi-modal

### ISSUE THREAD

**Issue by devinyf** [tmc/langchaingo#622]
current the Call method in Tool interface only allow text in and text out
```go
type Tool interface {
	Name() string
	Description() string
	Call(ctx context.Context, input string) (string, error)
}
```
I think it is reasonable to expand this implementation use ContentPart for image / video generation api tool

```go
type ContentPart interface {
	isPart()
}
```

Is this feasible ?

If that’s the case， I could try work on it.
Any suggestions ?

**Comment by bjwswang** [comment]
https://python.langchain.com/docs/integrations/tools/dalle_image_generator#run-as-a-tool-with-an-agent That's how python utilizes the image generation.  Make it a tool.

**Comment by devinyf** [comment]
In order to implementing this, I think it need to move the generatecontent.go and generatecontent_test.go 
from llms package to schema package...

because we need to use ContentPart interface in both tools and llms package
```sh
# before
llms/generatecontent.go
llms/generatecontent_test.go
# after
schema/generatecontent.go
schema/generatecontent_test.go
```
but that will  also need to update all the relevance files who imported something from this file

I'm not sure this would be a good way to approaching it... should I continue ?

Or just redefine a interface in tools package almost the same as ContentPart in llms package ??
```go
type ContentPart interface {
	isPart()
}
``` 

Which would be a better way ??
