### ISSUE TITLE
Callbacks:Will langchaingo consider implementing CallbackManager like langchain-python does

### ISSUE THREAD

**Issue by HymanShi** [tmc/langchaingo#637]
I'm working with langchaingo to create chains and agents. I found out that callbacks can not trace all the execution steps when I attempt to debug my agents or chains.I would like to have a [trace_id](https://smith.langchain.com/public/60909eae-f4f1-43eb-9f96-354f5176f66f/r/c9af1f3a-4b48-4140-aee7-dee3384e7af6) like langsmith does to display all the steps.
I also found that [CallbackManager](https://github.com/langchain-ai/langchain/blob/master/libs/core/langchain_core/callbacks/manager.py#L430) was implemented by langchain-python to manage callback handlers and use run_id/parent_run_id to trace all the steps. 
Will langchaingo consider implementing CallbackManager like langchain-python does?For example,**using** and **propagating** trace info(trace_id and span_id) in context.Context to connect all the steps would be useful.

**Comment by tmc** [comment]
We have an implementation of this as of https://github.com/tmc/langchaingo/pull/257
