### ISSUE TITLE
Recursive Similarity Search Feature

### ISSUE THREAD

**Issue by agcom** [tmc/langchaingo#645]
Basically, a vector store returns only `n` specified results back; to get all the results instead of just `n`, above a certain threshold score, one could use the recursive similarity search feature; this feature is already implemented in the corresponding JS library and it is described in [here](https://js.langchain.com/docs/modules/data_connection/retrievers/similarity-score-threshold-retriever).

My question is: is this feature available/implemented/used anywhere in `langchaingo`? If not, I would like to submit a PR.

**Comment by devalexandre** [comment]
@agcom it is equal a use 
```go 
optionsVector := []vectorstores.Option{
		vectorstores.WithScoreThreshold(0.80),
	}

	retriever := vectorstores.ToRetriever(store, 10, optionsVector...)
	
```

**Comment by agcom** [comment]
@devalexandre that would just return 10 documents at most, and that's the problem this issue is discussing; I need all the results above 0.8, not only 10.

A solution would be to set `numDocuments` to a large number; why do the recursive similarity search exists then?

Closing.

**Comment by devalexandre** [comment]
you can use a large number, but your implementation can be a good idea

**Comment by agcom** [comment]
I mean... now I don't even understand the point of the recursive similarity search; is there a use-case where a large number would not suffice?
