### ISSUE TITLE
[bug] cannot use llmChain (variable of type chains.LLMChain) as chains.Chain value in argument to chains.Run: missing method Call

### ISSUE THREAD

**Issue by JackBekket** [tmc/langchaingo#654]
My code:
```
        llm, err := openai.New()
	memory := memory.NewConversationBuffer()
         llmChain := chains.NewConversation(llm, memory)
         
         out, err := chains.Run(ctx, llmChain, "my name is xxx",
		chains.WithCallback(callbacks.StreamLogHandler{}),
		
	out2, err := chains.Run(ctx, llmChain, "what is my name ?",
		chains.WithCallback(callbacks.StreamLogHandler{}),
	)
```

expected behavior:
returned my name

actual behavior:
`cannot use llmChain (variable of type chains.LLMChain) as chains.Chain value in argument to chains.Run: missing method Call`

I have checked documents and find out that chain interface have method Call:
```
// Chain is the interface all chains must implement.
type Chain interface {
	// Call runs the logic of the chain and returns the output. This method should
	// not be called directly. Use rather the Call, Run or Predict functions that
	// handles the memory and other aspects of the chain.
	Call(ctx context.Context, inputs map[string]any, options ...ChainCallOption) (map[string]any, error)
	// GetMemory gets the memory of the chain.
	GetMemory() schema.Memory
	// GetInputKeys returns the input keys the chain expects.
	GetInputKeys() []string
	// GetOutputKeys returns the output keys the chain returns.
	GetOutputKeys() []string
}
```

But llm.go says:
```
type LLMChain struct {
	Prompt           prompts.FormatPrompter
	LLM              llms.Model
	Memory           schema.Memory
	CallbacksHandler callbacks.Handler
	OutputParser     schema.OutputParser[any]

	OutputKey string
}
```

Which means that LLMChain basically do not have Call method and this far is not compatible with Chain interface, and therefore you cannot use `chains.Run()` to execute the chain and I can't work with memory

It seems like https://github.com/tmc/langchaingo/pull/555 break it
Seems like it's @eliben work

so currently I can't use chains.Call, chains.Run and chains.Predict with LLM Chain

**Comment by devalexandre** [comment]
@JackBekket what version do you are using?

**Comment by JackBekket** [comment]
> @JackBekket what version do you are using?
> 
> I run your code and work
> 
> ```go
> 	llm, err := openai.New()
> 	memory := memory.NewConversationBuffer()
> 	llmChain := chains.NewConversation(llm, memory)
> 	ctx := context.Background()
> 	_, err = chains.Run(ctx, llmChain, "my name is xxx",
> 		chains.WithCallback(callbacks.StreamLogHandler{}),
> 	)
> 
> 	out2, err := chains.Run(ctx, llmChain, "what is my name ?",
> 		chains.WithCallback(callbacks.StreamLogHandler{}),
> 	)
> 
> 	if err != nil {
> 		log.Fatal(err)
> 	}
> 
> 	log.Println(out2)
> ```
> 
> I'm using te v0.1.5

v0.1.5 

Actually I've just succesed in running it, it seems like there was a problem with golang version -- I've used v.1.19, while there are v1.22 already

So, I've updated go version and it seems runnable from terminal, however IDE still thinks that there are no such method in that class

Ugh, I spent whole day trying to understand what's wrong and it seems now as IDE linter bug, I hope it will go away after reboot and cash clean

In any case my issue now seems unrelated to langchain itself, thanks for help!

**Comment by JackBekket** [comment]
Yout can mark it as completed now

**Comment by devalexandre** [comment]
@tmc  could close this :)
