### ISSUE TITLE
[Bug] openai function calling return error in v0.1.6

### ISSUE THREAD

**Issue by shawti** [tmc/langchaingo#689]
When I try running the examples/openai-function-call-streaming-example

I got the following error from openai api response:

API returned unexpected status code: 400: '' is not one of ['json_object', 'text'] - 'response_format.type'op

And I saw there is a  new opts `WithJSONMode` & a new field `ResponseFormat` in ChatRequest struct

I try setting the options `WithJSONMode` and I got a new error:

API returned unexpected status code: 400: 'messages' must contain the word 'json' in some form, to use 'response_format' of type 'json_object'.

I also try setting the options `WithResponseFormat` to `text` type when I new openai client, it is not take effect.

**Comment by victorguidi** [comment]
I can confirm this error, I just got it here using with Azure Open AI api, rolled back to version 0.1.4 and is working just fine.
