### ISSUE TITLE
llms: Add support integration with  perplexity

### ISSUE THREAD

**Issue by devalexandre** [tmc/langchaingo#692]
perplexity.ai, is an api for integration with models, as in the image below, unfortunately there is no support for enbeddings yet

![image](https://github.com/tmc/langchaingo/assets/4489558/6cc2c717-c6ab-42f3-b789-b626e979d54c)

**Comment by tmc** [comment]
This issue seems.. not super clearly written? I'm going to edit the title to add more intent -- please clean this up.

**Comment by devalexandre** [comment]
@tmc this issue are in #681
