### ISSUE TITLE
googleai: incorrect FinishReason when using StreamingFunc

### ISSUE THREAD

**Issue by suzmue** [tmc/langchaingo#728]
When using streaming API, the FinishReason in the response is not correctly set when the reason should be [FinishReasonMaxTokens](https://github.com/tmc/langchaingo/blob/b6ba6693d314adb5247ddb1e6bf246e989d56b2e/llms/googleai/googleai.go#L258).

This happens because on the last response, the content is empty, which leads it to return early without recording the FinishReason.
https://github.com/tmc/langchaingo/blob/b6ba6693d314adb5247ddb1e6bf246e989d56b2e/llms/googleai/googleai.go#L258

**Comment by tmc** [comment]
Thanks for the bug report, this should be straightforward to implement.
