### ISSUE TITLE
openai.WithEmbeddingModel option is incorrectly designating the desired model to use for embedding.

### ISSUE THREAD

**Issue by Dmarcotrigiano** [tmc/langchaingo#729]
`openai.WithEmbeddingModel("text-embedding-3-large")` is incorrectly  returning embeddings of length `1536`which is the default embedding length for models, `"text-embedding-3-small"` and `"ada-002"`.
Unintuitively setting the option `openai.WithModel("text-embedding-3-large")` correctly returns embeddings of length `3072`.

**Comment by tmc** [comment]
Fixed in #731
