### ISSUE TITLE
gemini (vertex): add tool function calling support

### ISSUE THREAD

**Issue by semanser** [tmc/langchaingo#748]
Hi, is there any specific reason why function calling wasn't implemented for Vertex in #709? I may give it a try, but I just want to make sure that there are no known blockers.

https://github.com/tmc/langchaingo/blob/33b87959129785199bea5ea743b745d784efb431/llms/googleai/googleai.go#L180-L183

Resources:
- https://pkg.go.dev/cloud.google.com/go/vertexai/genai#Tool
- https://cloud.google.com/vertex-ai/generative-ai/docs/multimodal/function-calling#overview

**Comment by semanser** [comment]
I started implementing this but immediately found an issue: function calling is supported in Vertex (`cloud.google.com/go/vertexai/genai`) but not in `github.com/google/generative-ai-go/genai`.

`vertex.go` is generated based on the `googleai.go` with the main difference that `GenerativeModel` returns different models in both files. That means that we can't use   `vertexGenAI "cloud.google.com/go/vertexai/genai"` inside of `googleai.go`...

<img width="841" alt="Screenshot 2024-04-02 at 18 01 52" src="https://github.com/tmc/langchaingo/assets/4020045/02838201-2006-4892-99be-c1fae10d0a80">
<img width="1337" alt="Screenshot 2024-04-02 at 18 02 07" src="https://github.com/tmc/langchaingo/assets/4020045/d4f66738-e0da-4665-be4e-8882c48d2b2c">

**Comment by eliben** [comment]
@semanser are you planning to continue working on this in the immediate future? I want this implemented, so I was thinking of tackling it myself unless you have a PR in progress already

**Comment by eliben** [comment]
#795 adds vertex ai support.

Next, an example and this issue can be closed
