### ISSUE TITLE
Add model parameter to openai.New()

### ISSUE THREAD

**Issue by bryanweingarten** [tmc/langchaingo#79]
The following `New` function in `llms/openai/openaillm.go` gets the `model` form either the environment, or from a default value in `llms/openai/internal/openaiclient/openaiclient.go`.  The default value is behind an `internal` package.   I propose that the `openai.New()` function a take an optional argument (using the optional function parameter pattern) that accepts an option for `model`.     This would easily and elegantly allow multiple instances to `openai.New()` to use different models and not be fixed to a single environment variable.

```
// New returns a new OpenAI client.
func New() (*LLM, error) {
	// Require the OpenAI API key to be set.
	token := os.Getenv(tokenEnvVarName)
	if token == "" {
		return nil, ErrMissingToken
	}

	// Allow model selection.
	model := os.Getenv(modelEnvVarName)

	// Create the client.
	c, err := openaiclient.New(token, model)
	return &LLM{
		client: c,
	}, err
}
```

**Comment by obitech** [comment]
This can be closed I guess? See #78

**Comment by cduggn** [comment]
Is it a necessity that the embedding model be an environment variable? These will be a finite set of values that could be defined as consts. Taking embeddings.NewOpenAI as an exmaple, there is a need to provide an embedding name however that detail is somewhat hidden in the creation of the openai.New() struct.

**Comment by tmc** [comment]
> Is it a necessity that the embedding model be an environment variable? These will be a finite set of values that could be defined as consts. Taking embeddings.NewOpenAI as an example, there is a need to provide an embedding name however that detail is somewhat hidden in the creation of the openai.New() struct which is called internally in the function and there is no comment which indicates the API Token and model are prerequisites

There's a balance here between making the default high level API as simple as possible. I'm taking cues from upstream on this front.

The openai.WithModel() option enables this so I'm considering it closed. Please feel free to raise any discussion or propose any changes.

**Comment by tmc** [comment]
(To clarify, this was fixed in https://github.com/tmc/langchaingo/pull/78)
