### ISSUE TITLE
请问有Tongyi Qwen的对接计划吗？

### ISSUE THREAD

**Issue by easynulls** [tmc/langchaingo#881]

**Comment by tmc** [comment]
Please write issue titles and descriptions in english please. Please consider adding an example showing use.

**Comment by tmc** [comment]
I'm going to close this as the linked issue overlaps, please feel free to pick up the conversation as you see fit.

**Comment by easynulls** [comment]
DashScope 模型服务灵积 https://dashscope.console.aliyun.com/

**Comment by easynulls** [comment]
Tanks.
